version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: kawtar001/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: miola
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  springboot-app:
    image: kawtar001/springboot:latest
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

    networks:
      - app-network

  react-frontend:
    image: kawtar001/react
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
